#Given: A DNA string s of length at most 1000 nt.
#Return: Four integers (separated by spaces) counting the respective number of times that the symbols 
#'A', 'C', 'G', and 'T' occur in s.

sir='CCCACCCCGCGAAAACAGGGGCCAAGTGGAAGACGTAGTGCAAGATAGAAGCGAACCTTCGTAAACATCAGCCCTTGGCCGTTGCTCCCCAAACGGAGCTATCGTAGCGCATGGCACGGATGGAACCAATAAGATTGCTTAGAGAACTGCTTGCTAGTCTACGTGAAAGCTAAGCACTGTGGTATCAGTATGACTGGGGGCCCTGTCATCATCCTACCCATAGGGCCCACCCCCTGCCCCGCAGATAGGTGATCGAGAAGACGAAGAGTACTCACGCGGGACTAAGGCGAGGGTAGGGCTTCTTGCGGTGAAACAGGGAGACGGAGAGTGCCCCGGTAGTTGAGGATCTATCCAATAACACGTGAGATACATGTCCCTGAACAGCGGTGGCCTTCACCGGCCTAACATCGGTCTGCCCTCGTCGGCAACTTGCTACGGAGATAGCATTTGAGCGCCAGACCTTCGAGGCTCTGCCAACAACCCTTACAAGCATGCAGATGAAGTGACGGCCTTCAGAAGCATATGGCCCGGATGTGTCAGGTTACGGTAAAACATGCAGTTCCCCCCACATATCGAACTTCATGGAGTCCCTGGGGTTTACGGTAGTCAGACTCGCGCCCCCGGTTGTGATTATTACACATCTATACTTTGGCCTTTGTGGCGTGCCCCAGAGGCGCCGAAATCTTGACATCAGTTGCCCTGTTAATGGCAACTAATGTTATCCGCCACCCTGCTAGAGCCTGCTACGCAGCAAACCCGATGTTGGGCACAAAGACGGCCTGTCAGCACACTCACATGCCCCATTACAACACGATAACAATG'
count_A=count_C=count_G=count_T=0
for (i in 1:nchar(sir))
{
  if (substring(sir,i,i)=='A')
  count_A=count_A+1
  else if (substring(sir,i,i)=='C')  
    count_C=count_C+1
  else if (substring(sir,i,i)=='G')  
    count_G=count_G+1
  else if (substring(sir,i,i)=='T')  
    count_T=count_T+1

}

c(count_A,count_C,count_G,count_T)