#Given: A DNA string s of length at most 1000 bp.
#Return: The reverse complement sc of s.

sir='TAGTTATGATTACTCGGTCACTGAGATGAGCGCCTTTATTACATATACCAGGATGGATGTATTGCCTAGTGCCCTGGCAGGTCGACTTACGAATTCGATGTGAAGCCCGGGGGTCTTGACCACCCGCTCAGTACTAGTTCGATACAAATCGGATCGTTTAGTGTTTTCCCTCCGAAAGTAGAAGATCTATTGGGGGCGGCTAAAATTATCAACTAACATTGGGTCACGGCCAATCATCGGTCCAAACCACGGAGTGGCTGAGGGGCCGTCTCGAACAATAACTAGTGGAGCGATCACCATGGAGATGATCCTGATCGCACCAGCCGTTATAATATCTCACGAGCCCTTCGTGCCAGCTTCAAAGCTATCTCCTAGCCGATCTTTAATACCAACAAGCCATTTCTGAAGCAGACATTTTACCCGCGCAACGAAGATGAGTTAAGATCCGATCTGTCAGCGCATCTGAATCTGCCAATTTTGTACACCGTCGCTCCAGCACGTGGGAGCGAACACATCCATTCAGCTATCCTTGGGCATCAGATCCACAGGGGTACCGATCATTGGGCGTTCAAAATTTTCAAACTAGGACAGCATCTTCGAAATGAAAGCAGGAGAGCTGCGCCGACTACGGTGGATCCATAATGCAGTGCAGTGGCAAGAGTACTTGGAATACAATCTCCTGCTCGGCGCTGGCGCCTCGGGGATCCCTTCATCGACTTATATAACTGGGGATTATCGGGGTCGGCCGGATAAGCTCACCTACTATATATAAGGTAATGCACAAACAAGTGGGATGGATGG'
for (i in 1:nchar(sir))
{
  if (substring(sir,i,i)=='T')
    substring(sir,i,i)='A'
  else if (substring(sir,i,i)=='A')
    substring(sir,i,i)='T'
  else if (substring(sir,i,i)=='C')
    substring(sir,i,i)='G'
  else if (substring(sir,i,i)=='G')
    substring(sir,i,i)='C'
}


sir

string_split <- strsplit(sir, NULL)[[1]]
string_split

reversed_string <- paste(rev(string_split), collapse="")
reversed_string
